### ISSUE TITLE
For volumes with replication to another region

### ISSUE THREAD

**Issue by daniel-liang** [ANFTechTeam/ANFCapacityManager#4]
It looks like it wont extend the passive volume size with endpointtype = 'Dst'

I am wondering what will happen if we remove the above condition check at 'Test if the Resource is an ANF Volume', as we are under the private review with ANF replication in Australia.

**Comment by seanluce** [comment]
Thank you, @daniel-liang.

Destination volumes now automatically resize when a source volume resizes. So the logic here is that we don't want to take action on CRR destination volumes directly. Instead only when the source volume triggers the app.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-resize-capacity-pools-or-volumes#resize-a-cross-region-replication-destination-volume
