### ISSUE TITLE
Volume Write Actions removing snapshot policy assignments

### ISSUE THREAD

**Issue by birdnathan** [ANFTechTeam/ANFCapacityManager#6]
When ANF Capacity Manager is performing Write Actions against a volume it is removing the Snapshot Policy assignments, this has been observed multiple times across different ANF Accounts and Volumes:

![image](https://user-images.githubusercontent.com/42775203/132651217-3a03e1e2-a9b6-43d2-b4dd-405c28bd5583.png)

![image](https://user-images.githubusercontent.com/42775203/132651395-2ddcee49-56d1-4f92-92ca-8ae3599776d5.png)

Snapshot policies have to be manually reapplied.

This is a major flaw, why is this?

**Comment by seanluce** [comment]
This was fixed back in April of this year. You'll need to re-deploy the app or manually change 'PUT' to 'PATCH' in a few places.

**Comment by birdnathan** [comment]
> This was fixed back in April of this year. You'll need to re-deploy the app or manually change 'PUT' to 'PATCH' in a few places.

I've redeployed the app, will keep an eye on that. Customer was running version 3.0. Missed that in the release notes. Thanks Sean!
